/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedOverdueRouteImport } from './routes/_authed/overdue'
import { Route as AuthedMapRouteImport } from './routes/_authed/map'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedVisitsIndexRouteImport } from './routes/_authed/visits/index'
import { Route as AuthedUsersIndexRouteImport } from './routes/_authed/users/index'
import { Route as AuthedTodayIndexRouteImport } from './routes/_authed/today/index'
import { Route as AuthedReportsIndexRouteImport } from './routes/_authed/reports/index'
import { Route as AuthedProductsIndexRouteImport } from './routes/_authed/products/index'
import { Route as AuthedDistributorsIndexRouteImport } from './routes/_authed/distributors/index'
import { Route as AuthedCustomersIndexRouteImport } from './routes/_authed/customers/index'
import { Route as AuthedCollectionRoutesIndexRouteImport } from './routes/_authed/collection-routes/index'
import { Route as AuthedBlacklistRequestsIndexRouteImport } from './routes/_authed/blacklist-requests/index'
import { Route as AuthedAuditIndexRouteImport } from './routes/_authed/audit/index'
import { Route as AuthedReceivablesNewRouteImport } from './routes/_authed/receivables/new'
import { Route as AuthedReceivablesIdRouteImport } from './routes/_authed/receivables/$id'
import { Route as AuthedProductsNewRouteImport } from './routes/_authed/products/new'
import { Route as AuthedProductsIdRouteImport } from './routes/_authed/products/$id'
import { Route as AuthedDistributorsNewRouteImport } from './routes/_authed/distributors/new'
import { Route as AuthedCustomersNewRouteImport } from './routes/_authed/customers/new'
import { Route as AuthedCustomersMissingLocationRouteImport } from './routes/_authed/customers/missing-location'
import { Route as AuthedCustomersIdRouteImport } from './routes/_authed/customers/$id'
import { Route as AuthedProductsIdEditRouteImport } from './routes/_authed/products/$id_.edit'
import { Route as AuthedDistributorsIdEditRouteImport } from './routes/_authed/distributors/$id.edit'
import { Route as AuthedCustomersIdEditRouteImport } from './routes/_authed/customers/$id_.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOverdueRoute = AuthedOverdueRouteImport.update({
  id: '/overdue',
  path: '/overdue',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMapRoute = AuthedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedVisitsIndexRoute = AuthedVisitsIndexRouteImport.update({
  id: '/visits/',
  path: '/visits/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsersIndexRoute = AuthedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTodayIndexRoute = AuthedTodayIndexRouteImport.update({
  id: '/today/',
  path: '/today/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsIndexRoute = AuthedReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsIndexRoute = AuthedProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDistributorsIndexRoute = AuthedDistributorsIndexRouteImport.update({
  id: '/distributors/',
  path: '/distributors/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCustomersIndexRoute = AuthedCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCollectionRoutesIndexRoute =
  AuthedCollectionRoutesIndexRouteImport.update({
    id: '/collection-routes/',
    path: '/collection-routes/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedBlacklistRequestsIndexRoute =
  AuthedBlacklistRequestsIndexRouteImport.update({
    id: '/blacklist-requests/',
    path: '/blacklist-requests/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAuditIndexRoute = AuthedAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReceivablesNewRoute = AuthedReceivablesNewRouteImport.update({
  id: '/receivables/new',
  path: '/receivables/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReceivablesIdRoute = AuthedReceivablesIdRouteImport.update({
  id: '/receivables/$id',
  path: '/receivables/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsNewRoute = AuthedProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsIdRoute = AuthedProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDistributorsNewRoute = AuthedDistributorsNewRouteImport.update({
  id: '/distributors/new',
  path: '/distributors/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCustomersNewRoute = AuthedCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCustomersMissingLocationRoute =
  AuthedCustomersMissingLocationRouteImport.update({
    id: '/customers/missing-location',
    path: '/customers/missing-location',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCustomersIdRoute = AuthedCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsIdEditRoute = AuthedProductsIdEditRouteImport.update({
  id: '/products/$id_/edit',
  path: '/products/$id/edit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDistributorsIdEditRoute =
  AuthedDistributorsIdEditRouteImport.update({
    id: '/distributors/$id/edit',
    path: '/distributors/$id/edit',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCustomersIdEditRoute = AuthedCustomersIdEditRouteImport.update({
  id: '/customers/$id_/edit',
  path: '/customers/$id/edit',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/map': typeof AuthedMapRoute
  '/overdue': typeof AuthedOverdueRoute
  '/customers/$id': typeof AuthedCustomersIdRoute
  '/customers/missing-location': typeof AuthedCustomersMissingLocationRoute
  '/customers/new': typeof AuthedCustomersNewRoute
  '/distributors/new': typeof AuthedDistributorsNewRoute
  '/products/$id': typeof AuthedProductsIdRoute
  '/products/new': typeof AuthedProductsNewRoute
  '/receivables/$id': typeof AuthedReceivablesIdRoute
  '/receivables/new': typeof AuthedReceivablesNewRoute
  '/audit/': typeof AuthedAuditIndexRoute
  '/blacklist-requests/': typeof AuthedBlacklistRequestsIndexRoute
  '/collection-routes/': typeof AuthedCollectionRoutesIndexRoute
  '/customers/': typeof AuthedCustomersIndexRoute
  '/distributors/': typeof AuthedDistributorsIndexRoute
  '/products/': typeof AuthedProductsIndexRoute
  '/reports/': typeof AuthedReportsIndexRoute
  '/today/': typeof AuthedTodayIndexRoute
  '/users/': typeof AuthedUsersIndexRoute
  '/visits/': typeof AuthedVisitsIndexRoute
  '/customers/$id/edit': typeof AuthedCustomersIdEditRoute
  '/distributors/$id/edit': typeof AuthedDistributorsIdEditRoute
  '/products/$id/edit': typeof AuthedProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/map': typeof AuthedMapRoute
  '/overdue': typeof AuthedOverdueRoute
  '/customers/$id': typeof AuthedCustomersIdRoute
  '/customers/missing-location': typeof AuthedCustomersMissingLocationRoute
  '/customers/new': typeof AuthedCustomersNewRoute
  '/distributors/new': typeof AuthedDistributorsNewRoute
  '/products/$id': typeof AuthedProductsIdRoute
  '/products/new': typeof AuthedProductsNewRoute
  '/receivables/$id': typeof AuthedReceivablesIdRoute
  '/receivables/new': typeof AuthedReceivablesNewRoute
  '/audit': typeof AuthedAuditIndexRoute
  '/blacklist-requests': typeof AuthedBlacklistRequestsIndexRoute
  '/collection-routes': typeof AuthedCollectionRoutesIndexRoute
  '/customers': typeof AuthedCustomersIndexRoute
  '/distributors': typeof AuthedDistributorsIndexRoute
  '/products': typeof AuthedProductsIndexRoute
  '/reports': typeof AuthedReportsIndexRoute
  '/today': typeof AuthedTodayIndexRoute
  '/users': typeof AuthedUsersIndexRoute
  '/visits': typeof AuthedVisitsIndexRoute
  '/customers/$id/edit': typeof AuthedCustomersIdEditRoute
  '/distributors/$id/edit': typeof AuthedDistributorsIdEditRoute
  '/products/$id/edit': typeof AuthedProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/map': typeof AuthedMapRoute
  '/_authed/overdue': typeof AuthedOverdueRoute
  '/_authed/customers/$id': typeof AuthedCustomersIdRoute
  '/_authed/customers/missing-location': typeof AuthedCustomersMissingLocationRoute
  '/_authed/customers/new': typeof AuthedCustomersNewRoute
  '/_authed/distributors/new': typeof AuthedDistributorsNewRoute
  '/_authed/products/$id': typeof AuthedProductsIdRoute
  '/_authed/products/new': typeof AuthedProductsNewRoute
  '/_authed/receivables/$id': typeof AuthedReceivablesIdRoute
  '/_authed/receivables/new': typeof AuthedReceivablesNewRoute
  '/_authed/audit/': typeof AuthedAuditIndexRoute
  '/_authed/blacklist-requests/': typeof AuthedBlacklistRequestsIndexRoute
  '/_authed/collection-routes/': typeof AuthedCollectionRoutesIndexRoute
  '/_authed/customers/': typeof AuthedCustomersIndexRoute
  '/_authed/distributors/': typeof AuthedDistributorsIndexRoute
  '/_authed/products/': typeof AuthedProductsIndexRoute
  '/_authed/reports/': typeof AuthedReportsIndexRoute
  '/_authed/today/': typeof AuthedTodayIndexRoute
  '/_authed/users/': typeof AuthedUsersIndexRoute
  '/_authed/visits/': typeof AuthedVisitsIndexRoute
  '/_authed/customers/$id_/edit': typeof AuthedCustomersIdEditRoute
  '/_authed/distributors/$id/edit': typeof AuthedDistributorsIdEditRoute
  '/_authed/products/$id_/edit': typeof AuthedProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/map'
    | '/overdue'
    | '/customers/$id'
    | '/customers/missing-location'
    | '/customers/new'
    | '/distributors/new'
    | '/products/$id'
    | '/products/new'
    | '/receivables/$id'
    | '/receivables/new'
    | '/audit/'
    | '/blacklist-requests/'
    | '/collection-routes/'
    | '/customers/'
    | '/distributors/'
    | '/products/'
    | '/reports/'
    | '/today/'
    | '/users/'
    | '/visits/'
    | '/customers/$id/edit'
    | '/distributors/$id/edit'
    | '/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/map'
    | '/overdue'
    | '/customers/$id'
    | '/customers/missing-location'
    | '/customers/new'
    | '/distributors/new'
    | '/products/$id'
    | '/products/new'
    | '/receivables/$id'
    | '/receivables/new'
    | '/audit'
    | '/blacklist-requests'
    | '/collection-routes'
    | '/customers'
    | '/distributors'
    | '/products'
    | '/reports'
    | '/today'
    | '/users'
    | '/visits'
    | '/customers/$id/edit'
    | '/distributors/$id/edit'
    | '/products/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/map'
    | '/_authed/overdue'
    | '/_authed/customers/$id'
    | '/_authed/customers/missing-location'
    | '/_authed/customers/new'
    | '/_authed/distributors/new'
    | '/_authed/products/$id'
    | '/_authed/products/new'
    | '/_authed/receivables/$id'
    | '/_authed/receivables/new'
    | '/_authed/audit/'
    | '/_authed/blacklist-requests/'
    | '/_authed/collection-routes/'
    | '/_authed/customers/'
    | '/_authed/distributors/'
    | '/_authed/products/'
    | '/_authed/reports/'
    | '/_authed/today/'
    | '/_authed/users/'
    | '/_authed/visits/'
    | '/_authed/customers/$id_/edit'
    | '/_authed/distributors/$id/edit'
    | '/_authed/products/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/overdue': {
      id: '/_authed/overdue'
      path: '/overdue'
      fullPath: '/overdue'
      preLoaderRoute: typeof AuthedOverdueRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/map': {
      id: '/_authed/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthedMapRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/visits/': {
      id: '/_authed/visits/'
      path: '/visits'
      fullPath: '/visits/'
      preLoaderRoute: typeof AuthedVisitsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/users/': {
      id: '/_authed/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthedUsersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/today/': {
      id: '/_authed/today/'
      path: '/today'
      fullPath: '/today/'
      preLoaderRoute: typeof AuthedTodayIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports/': {
      id: '/_authed/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthedReportsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/': {
      id: '/_authed/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthedProductsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/distributors/': {
      id: '/_authed/distributors/'
      path: '/distributors'
      fullPath: '/distributors/'
      preLoaderRoute: typeof AuthedDistributorsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customers/': {
      id: '/_authed/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthedCustomersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/collection-routes/': {
      id: '/_authed/collection-routes/'
      path: '/collection-routes'
      fullPath: '/collection-routes/'
      preLoaderRoute: typeof AuthedCollectionRoutesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/blacklist-requests/': {
      id: '/_authed/blacklist-requests/'
      path: '/blacklist-requests'
      fullPath: '/blacklist-requests/'
      preLoaderRoute: typeof AuthedBlacklistRequestsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit/': {
      id: '/_authed/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuthedAuditIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/receivables/new': {
      id: '/_authed/receivables/new'
      path: '/receivables/new'
      fullPath: '/receivables/new'
      preLoaderRoute: typeof AuthedReceivablesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/receivables/$id': {
      id: '/_authed/receivables/$id'
      path: '/receivables/$id'
      fullPath: '/receivables/$id'
      preLoaderRoute: typeof AuthedReceivablesIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/new': {
      id: '/_authed/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthedProductsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/$id': {
      id: '/_authed/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthedProductsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/distributors/new': {
      id: '/_authed/distributors/new'
      path: '/distributors/new'
      fullPath: '/distributors/new'
      preLoaderRoute: typeof AuthedDistributorsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customers/new': {
      id: '/_authed/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AuthedCustomersNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customers/missing-location': {
      id: '/_authed/customers/missing-location'
      path: '/customers/missing-location'
      fullPath: '/customers/missing-location'
      preLoaderRoute: typeof AuthedCustomersMissingLocationRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customers/$id': {
      id: '/_authed/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthedCustomersIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/$id_/edit': {
      id: '/_authed/products/$id_/edit'
      path: '/products/$id/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof AuthedProductsIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/distributors/$id/edit': {
      id: '/_authed/distributors/$id/edit'
      path: '/distributors/$id/edit'
      fullPath: '/distributors/$id/edit'
      preLoaderRoute: typeof AuthedDistributorsIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customers/$id_/edit': {
      id: '/_authed/customers/$id_/edit'
      path: '/customers/$id/edit'
      fullPath: '/customers/$id/edit'
      preLoaderRoute: typeof AuthedCustomersIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedMapRoute: typeof AuthedMapRoute
  AuthedOverdueRoute: typeof AuthedOverdueRoute
  AuthedCustomersIdRoute: typeof AuthedCustomersIdRoute
  AuthedCustomersMissingLocationRoute: typeof AuthedCustomersMissingLocationRoute
  AuthedCustomersNewRoute: typeof AuthedCustomersNewRoute
  AuthedDistributorsNewRoute: typeof AuthedDistributorsNewRoute
  AuthedProductsIdRoute: typeof AuthedProductsIdRoute
  AuthedProductsNewRoute: typeof AuthedProductsNewRoute
  AuthedReceivablesIdRoute: typeof AuthedReceivablesIdRoute
  AuthedReceivablesNewRoute: typeof AuthedReceivablesNewRoute
  AuthedAuditIndexRoute: typeof AuthedAuditIndexRoute
  AuthedBlacklistRequestsIndexRoute: typeof AuthedBlacklistRequestsIndexRoute
  AuthedCollectionRoutesIndexRoute: typeof AuthedCollectionRoutesIndexRoute
  AuthedCustomersIndexRoute: typeof AuthedCustomersIndexRoute
  AuthedDistributorsIndexRoute: typeof AuthedDistributorsIndexRoute
  AuthedProductsIndexRoute: typeof AuthedProductsIndexRoute
  AuthedReportsIndexRoute: typeof AuthedReportsIndexRoute
  AuthedTodayIndexRoute: typeof AuthedTodayIndexRoute
  AuthedUsersIndexRoute: typeof AuthedUsersIndexRoute
  AuthedVisitsIndexRoute: typeof AuthedVisitsIndexRoute
  AuthedCustomersIdEditRoute: typeof AuthedCustomersIdEditRoute
  AuthedDistributorsIdEditRoute: typeof AuthedDistributorsIdEditRoute
  AuthedProductsIdEditRoute: typeof AuthedProductsIdEditRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedMapRoute: AuthedMapRoute,
  AuthedOverdueRoute: AuthedOverdueRoute,
  AuthedCustomersIdRoute: AuthedCustomersIdRoute,
  AuthedCustomersMissingLocationRoute: AuthedCustomersMissingLocationRoute,
  AuthedCustomersNewRoute: AuthedCustomersNewRoute,
  AuthedDistributorsNewRoute: AuthedDistributorsNewRoute,
  AuthedProductsIdRoute: AuthedProductsIdRoute,
  AuthedProductsNewRoute: AuthedProductsNewRoute,
  AuthedReceivablesIdRoute: AuthedReceivablesIdRoute,
  AuthedReceivablesNewRoute: AuthedReceivablesNewRoute,
  AuthedAuditIndexRoute: AuthedAuditIndexRoute,
  AuthedBlacklistRequestsIndexRoute: AuthedBlacklistRequestsIndexRoute,
  AuthedCollectionRoutesIndexRoute: AuthedCollectionRoutesIndexRoute,
  AuthedCustomersIndexRoute: AuthedCustomersIndexRoute,
  AuthedDistributorsIndexRoute: AuthedDistributorsIndexRoute,
  AuthedProductsIndexRoute: AuthedProductsIndexRoute,
  AuthedReportsIndexRoute: AuthedReportsIndexRoute,
  AuthedTodayIndexRoute: AuthedTodayIndexRoute,
  AuthedUsersIndexRoute: AuthedUsersIndexRoute,
  AuthedVisitsIndexRoute: AuthedVisitsIndexRoute,
  AuthedCustomersIdEditRoute: AuthedCustomersIdEditRoute,
  AuthedDistributorsIdEditRoute: AuthedDistributorsIdEditRoute,
  AuthedProductsIdEditRoute: AuthedProductsIdEditRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
