/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedMapRouteImport } from './routes/_authed/map'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedCustomersIndexRouteImport } from './routes/_authed/customers/index'
import { Route as AuthedReceivablesNewRouteImport } from './routes/_authed/receivables/new'
import { Route as AuthedReceivablesIdRouteImport } from './routes/_authed/receivables/$id'
import { Route as AuthedCustomersNewRouteImport } from './routes/_authed/customers/new'
import { Route as AuthedCustomersIdRouteImport } from './routes/_authed/customers/$id'
import { Route as AuthedCustomersIdEditRouteImport } from './routes/_authed/customers/$id_.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMapRoute = AuthedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCustomersIndexRoute = AuthedCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReceivablesNewRoute = AuthedReceivablesNewRouteImport.update({
  id: '/receivables/new',
  path: '/receivables/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReceivablesIdRoute = AuthedReceivablesIdRouteImport.update({
  id: '/receivables/$id',
  path: '/receivables/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCustomersNewRoute = AuthedCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCustomersIdRoute = AuthedCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCustomersIdEditRoute = AuthedCustomersIdEditRouteImport.update({
  id: '/customers/$id_/edit',
  path: '/customers/$id/edit',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/map': typeof AuthedMapRoute
  '/customers/$id': typeof AuthedCustomersIdRoute
  '/customers/new': typeof AuthedCustomersNewRoute
  '/receivables/$id': typeof AuthedReceivablesIdRoute
  '/receivables/new': typeof AuthedReceivablesNewRoute
  '/customers/': typeof AuthedCustomersIndexRoute
  '/customers/$id/edit': typeof AuthedCustomersIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/map': typeof AuthedMapRoute
  '/customers/$id': typeof AuthedCustomersIdRoute
  '/customers/new': typeof AuthedCustomersNewRoute
  '/receivables/$id': typeof AuthedReceivablesIdRoute
  '/receivables/new': typeof AuthedReceivablesNewRoute
  '/customers': typeof AuthedCustomersIndexRoute
  '/customers/$id/edit': typeof AuthedCustomersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/map': typeof AuthedMapRoute
  '/_authed/customers/$id': typeof AuthedCustomersIdRoute
  '/_authed/customers/new': typeof AuthedCustomersNewRoute
  '/_authed/receivables/$id': typeof AuthedReceivablesIdRoute
  '/_authed/receivables/new': typeof AuthedReceivablesNewRoute
  '/_authed/customers/': typeof AuthedCustomersIndexRoute
  '/_authed/customers/$id_/edit': typeof AuthedCustomersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/map'
    | '/customers/$id'
    | '/customers/new'
    | '/receivables/$id'
    | '/receivables/new'
    | '/customers/'
    | '/customers/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/map'
    | '/customers/$id'
    | '/customers/new'
    | '/receivables/$id'
    | '/receivables/new'
    | '/customers'
    | '/customers/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/map'
    | '/_authed/customers/$id'
    | '/_authed/customers/new'
    | '/_authed/receivables/$id'
    | '/_authed/receivables/new'
    | '/_authed/customers/'
    | '/_authed/customers/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/map': {
      id: '/_authed/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthedMapRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customers/': {
      id: '/_authed/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthedCustomersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/receivables/new': {
      id: '/_authed/receivables/new'
      path: '/receivables/new'
      fullPath: '/receivables/new'
      preLoaderRoute: typeof AuthedReceivablesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/receivables/$id': {
      id: '/_authed/receivables/$id'
      path: '/receivables/$id'
      fullPath: '/receivables/$id'
      preLoaderRoute: typeof AuthedReceivablesIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customers/new': {
      id: '/_authed/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AuthedCustomersNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customers/$id': {
      id: '/_authed/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthedCustomersIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customers/$id_/edit': {
      id: '/_authed/customers/$id_/edit'
      path: '/customers/$id/edit'
      fullPath: '/customers/$id/edit'
      preLoaderRoute: typeof AuthedCustomersIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedMapRoute: typeof AuthedMapRoute
  AuthedCustomersIdRoute: typeof AuthedCustomersIdRoute
  AuthedCustomersNewRoute: typeof AuthedCustomersNewRoute
  AuthedReceivablesIdRoute: typeof AuthedReceivablesIdRoute
  AuthedReceivablesNewRoute: typeof AuthedReceivablesNewRoute
  AuthedCustomersIndexRoute: typeof AuthedCustomersIndexRoute
  AuthedCustomersIdEditRoute: typeof AuthedCustomersIdEditRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedMapRoute: AuthedMapRoute,
  AuthedCustomersIdRoute: AuthedCustomersIdRoute,
  AuthedCustomersNewRoute: AuthedCustomersNewRoute,
  AuthedReceivablesIdRoute: AuthedReceivablesIdRoute,
  AuthedReceivablesNewRoute: AuthedReceivablesNewRoute,
  AuthedCustomersIndexRoute: AuthedCustomersIndexRoute,
  AuthedCustomersIdEditRoute: AuthedCustomersIdEditRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
